[[items]]
title = "KARAKURI"
subtitle = "Tokyo 7th Sisters"
description = "由秋奈演绎，Tokyo-7th的同卵双胞胎双子组合空栗一叶/空栗双叶。音色空灵，情感丰富。"
link = "https://t7s.jp/character/unit/10.html"
theme_color = "#8d62d3"
[items.trailer]
title = "《B.A.A.B》"
link = "https://www.bilibili.com/video/av18527451/"

[[items]]
title = "レイジー・レイジー"
subtitle = "アイドルマスター シンデレラガールズ"
description = "宫本芙蕾德莉卡 (CV.髙野麻美) 和一之濑志希 (CV.藍原ことみ) 组成的组合。组合代表曲是由TAKU INOUE制作的《クレイジークレイジー》，Jersey Club神曲。"
theme_color = "#d33261"
[items.trailer]
title = "《クレイジークレイジー》 (SS3A ver.)"
link = "https://www.bilibili.com/video/av226239930/"

[[items]]
title = "星宮とと"
description = "数字艺术家，兼做歌手/企划/设计/视频制作等。形象是白毛灰衣蓝瞳妹子，声音柔和。"
link = "https://hoshimiyatoto.com/"
theme_color = "#f3f3f3"
[items.trailer]
title = "星宮とと×TEMPLIME - 《純粋》"
link = "https://www.youtube.com/watch?v=2ahue0rfPLw"

[[items]]
title = "somunia"
description = "在互联网某处的一室栖息和歌唱的少女，蓝发有角但是没有三倍速。YouTube上最出名的曲目是和 nyankobrq & yaca 合作，接近千万播放量的《twinkle light》。"
link = "https://somunia.net/"
theme_color = "#89aed7"
[items.trailer]
title = "Special Mini Live \"reverie\""
link = "https://www.youtube.com/watch?v=llUc6VZyHLw"

[[items]]
title = "Marpril"
description = "由谷田透佳和立花铃组成的双人组合。除了引人入胜的音乐之外，精致的3D建模和动感的舞步也是Marpril的亮点。"
link = "https://www.youtube.com/@MarprilChannel"
theme_color = "#a347ff"
[items.trailer]
title = "PSYQUI feat. Marirl - Girly Cupid"
link = "https://www.youtube.com/watch?v=8gAN3hUiVAQ"

[[items]]
title = "アズマリム"
description = "梓璃梦是之前以可爱后辈，现在以本田小狼C125为特点的VTuber。大概是最命运多舛的VTuber之一：中之人更换危机、遭受骨折之疾、工资问题……总之最后成为了个人势VTuber。"
link = "https://www.youtube.com/@Azumalim"
theme_color = "#d8c8ed"
[items.trailer]
title = "虚拟JK、首次挑战露营!孤零零的也能做到!大概…。"
link = "https://www.bilibili.com/video/av466417018/"

[[items]]
title = "Photon Maiden"
subtitle = "D4DJ"
description = "由出云咲姬（CV.纺木吏佐）、新岛衣舞纪（CV.前岛亚美→七木奏音）、花卷乙和（CV.岩田阳葵）、福岛诺亚（CV.佐藤日向）组成的团体。曲目多为EDM风格，歌词含有英文的情况也较多。偏梦幻色彩的组合，只要别想起来C位的CV是纺木吏佐……"
link = "https://d4dj-pj.com/character/#photon-maiden"
theme_color = "#0b8083"
[items.trailer]
title = "《Be with the world》 (live)"
link = "https://www.bilibili.com/video/av292981039/"
