[[morelove]]
title = "電音部Love"
link = "https://aka.yt/denonbulove"

[[morelove]]
title = "THE IDOLM@STER Love"
link = "https://aka.yt/imaslove"

[[items]]
title = "KARAKURI"
subtitle = "Tokyo 7th Sisters"
description = "由秋奈演绎，Tokyo-7th的同卵双胞胎双子组合空栗一叶/空栗双叶。音色空灵，情感丰富。"
link = "https://t7s.jp/character/unit/10.html"
theme_color = "#8d62d3"
order = 1
[items.trailer]
title = "《B.A.A.B》"
link = "https://www.bilibili.com/video/av18527451/"

[[items]]
title = "レイジー・レイジー"
subtitle = "アイドルマスター シンデレラガールズ"
description = "宫本芙蕾德莉卡 (CV.髙野麻美) 和一之濑志希 (CV.藍原ことみ) 组成的组合。组合代表曲是由TAKU INOUE制作的《クレイジークレイジー》，Jersey Club神曲。"
theme_color = "#d33261"
[items.trailer]
title = "《クレイジークレイジー》 (SS3A ver.)"
link = "https://www.bilibili.com/video/av226239930/"

[[items]]
title = "星宮とと"
description = "数字艺术家，兼做歌手/企划/设计/视频制作等。形象是白毛灰衣蓝瞳妹子，声音柔和。"
link = "https://hoshimiyatoto.com/"
theme_color = "#f3f3f3"
[items.trailer]
title = "星宮とと×TEMPLIME - 《純粋》"
link = "https://www.youtube.com/watch?v=2ahue0rfPLw"

[[items]]
title = "somunia"
description = "在互联网某处的一室栖息和歌唱的少女，蓝发有角但是没有三倍速。YouTube上最出名的曲目是和 nyankobrq & yaca 合作，接近千万播放量的《twinkle light》。"
link = "https://somunia.net/"
theme_color = "#89aed7"
[items.trailer]
title = "Special Mini Live \"reverie\""
link = "https://www.youtube.com/watch?v=llUc6VZyHLw"

[[items]]
title = "Marpril"
description = "由谷田透佳和立花铃组成的双人组合。除了引人入胜的音乐之外，精致的3D建模和动感的舞步也是Marpril的亮点。"
link = "https://www.youtube.com/@MarprilChannel"
theme_color = "#a347ff"
[items.trailer]
title = "PSYQUI feat. Marirl - Girly Cupid"
link = "https://www.youtube.com/watch?v=8gAN3hUiVAQ"

[[items]]
title = "アズマリム"
description = "梓璃梦是之前以可爱后辈，现在以本田小狼C125为特点的VTuber。大概是最命运多舛的VTuber之一：中之人更换危机、遭受骨折之疾、工资问题……总之最后成为了个人势VTuber。"
link = "https://www.youtube.com/@Azumalim"
theme_color = "#d8c8ed"
[items.trailer]
title = "虚拟JK、首次挑战露营!孤零零的也能做到!大概…。"
link = "https://www.bilibili.com/video/av466417018/"

[[items]]
title = "Photon Maiden"
subtitle = "D4DJ"
description = "由出云咲姬（CV.纺木吏佐）、新岛衣舞纪（CV.前岛亚美→七木奏音）、花卷乙和（CV.岩田阳葵）、福岛诺亚（CV.佐藤日向）组成的团体。曲目多为EDM风格，歌词含有英文的情况也较多。偏梦幻色彩的组合，只要别想起来C位的CV是纺木吏佐……"
link = "https://d4dj-pj.com/character/#photon-maiden"
theme_color = "#0b8083"
[items.trailer]
title = "《暁》 (live)"
link = "https://www.bilibili.com/video/av114114546439072/"

[[items]]
title = "港白金女学院"
subtitle = "電音部"
description = "由黒鉄たま(CV.秋奈)、白金煌(CV.小宮有紗)、灰島銀華(CV.澁谷梓希)组成的团体。中之人都是电音大手：秋奈声线清奇、澁谷梓希是 AZK 名义的 DJ，小宫有纱更是水团电音王。"
link = "https://denonbu.jp/area/azabu"
theme_color = "#000000"
[items.trailer]
# 本来打算找一首非 cover 曲，但是 live 上三人组均参与演唱的原创曲不太多（例如电音部的 4th live 上三人就没能共同作为港白金组出场）。这场 live 在这曲之前的《Love Me Harder》虽然也符合这个要求也很好听，但 remix 太普通了。
title = "《pop enemy》 (cover, 電音部 アザブエリア 2nd live)"
link = "https://www.bilibili.com/video/av1652235937/?t=1590"

[[items]]
title = "ミライアカリ"
description = "VTuber四天王之一。官方中文译名「未来明」（不过我比较喜欢烤肉man旅人老师的译名「满星光」）。2023年引退。初始形象由KEI设计。中之人性格开朗、声线多变、唱歌好听、擅长造梗，而且综艺感强。Akari可以说是我开始看VTuber的契机。"
link = "https://youtube.com/@bittranslate"
theme_color = "#57acf8"
[items.trailer]
title = "《ロキ》 (cover)"
link = "https://www.youtube.com/watch?v=f_3t9AhqnUw"

[[items]]
title = "DOLLCHESTRA"
subtitle = "Love Live! 蓮ノ空女学院スクールアイドルクラブ"
description = "由村野沙耶香（CV.野中心菜）、徒町小铃（CV.叶山风花）、夕雾缀理（CV.佐佐木琴子，已毕业）组成的团体。曲风偏抒情。脱线的前辈和靠谱的后辈，后辈照顾前辈的样子太可爱了。"
theme_color = "#205aa7"
[items.trailer]
title = "《ジブンダイアリー》 (1st live tour ver.)"
link = "https://www.bilibili.com/video/av323590720/"
